### ISSUE TITLE
Save friendly name (and possibly a longer comment too) inside a peer config file

### ISSUE THREAD

**Issue by sskras** [sskras/wg-peers#7]
That could go as an extension of the `peer: ...` line, like it's done in [ndfan77/wgw](https://github.com/ndfan77/wgw):

![image](https://github.com/ndfan77/wgw/raw/main/WGW-ExampleScreen.png)

... or as an additional line inserted after the `peer: ...` line, like it's done in [FlyveHest/wg-friendly-peer-names](https://github.com/FlyveHest/wg-friendly-peer-names):

```yaml
peer: 0123456789abcdef0123456789abcdef0123456789a=
  friendly name: A friendly peer name
  endpoint: 127.0.0.1:12345
  allowed ips: 127.0.0.2/32
  latest handshake: 2 hours, 4 minutes, 15 seconds ago
  transfer: 84.60 MiB received, 94.05 MiB sent
```
